// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.opt.v0_1.types;

/** WIT-generated record. */
public record Config(java.util.Optional<String> name, java.util.Optional<java.util.Optional<Long>> retries) {
}
