// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.opt.v0_1.types;

import java.util.Optional;

/** Configuration.
 *
 * @param name name
 * @param retries retries
 */
public record Config(Optional<String> name, Optional<Optional<Long>> retries) {}
