// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.opt.v0_1.types;

/** WIT interface. */
public interface Types {

    /** Unsigned 64-bit integer, range 0..2^64-1, stored as a Java {@code long}, which is signed. Use {@link java.lang.Long#compareUnsigned}, {@link java.lang.Long#divideUnsigned} and {@link java.lang.Long#toUnsignedString} for unsigned operations. */
    java.util.Optional<Long> probe(java.util.Optional<Integer> depth);
}
