// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.opt.v0_1.types;

import java.util.Optional;

/** Nothing to see here. */
public interface Types {

    /** Probe.
     *
     * @param depth depth
     * @return probe
     */
    Optional<Long> probe(Optional<Integer> depth);
}
