// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.feat.v0_1.app.guest;

import demo.feat.v0_1.types.Types;

/** World imports. Called by the guest; provided by the host. */
public interface Imports {

    /** Access the imported interface. */
    Types types();
}
