// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.class_.v1.default_.guest;

import demo.class_.v1.inner.Box;

/** World exports. Implemented by the guest; called by the host. */
public interface Exports {

    void go(Box x);
}
