// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.class_.v1.default_.guest;

import demo.class_.v1.inner.Inner;

/** World imports. Called by the guest; provided by the host. */
public interface Imports {

    /** Access the imported interface. */
    Inner inner();
}
