// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.app.v0_2.machine.guest;

/** World exports. Implemented by the guest; called by the host. */
public interface Exports {

    /** start.
     */
    void start();
}
