// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.app.v0_2.machine.guest;

import demo.app.v0_2.logging.Logging;

/** World imports. Called by the guest; provided by the host. */
public interface Imports {

    /** Access the imported interface. */
    Logging logging();

    int ping();
}
