// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.inline.v1.broker.guest;

/** World exports. Implemented by the guest; called by the host. */
public interface Exports {

    void log(String msg);
}
