// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.inline.v1.broker.guest;

import demo.inline.v1.broker.Payload;
import demo.inline.v1.broker.Severity;

/** World imports. Called by the guest; provided by the host. */
public interface Imports {

    /**
     * @param p Unsigned 64-bit integer, range 0..2^64-1, stored as a Java {@code long}, which is signed. Use {@link java.lang.Long#compareUnsigned}, {@link java.lang.Long#divideUnsigned} and {@link java.lang.Long#toUnsignedString} for unsigned operations.
     */
    Severity onEvent(Severity sev, Payload p);
}
