// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.app.v0_2.logging;

/** Nothing to see here. */
public interface Logging {

    /** Write a line.
     *
     * @param msg msg
     */
    void log(String msg);
}
