// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.feat.v0_1.app.host;

import demo.feat.v0_1.types.Types;

/** World imports. Implemented by the host; called by the component. */
public interface Imports {

    /** Access the imported interface. */
    Types types();
}
