// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.empty.v0_1.app.guest;

import demo.empty.v0_1.used.Used;

/** World imports. Called by the guest; provided by the host. */
public interface Imports {

    /** Access the imported interface. */
    Used used();
}
