// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.class_.v1.default_.host;

import demo.class_.v1.inner.Box;

/** World exports. Called by the host; implemented by the component. */
public interface Exports {

    void go(Box x);
}
