// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.class_.v1.default_.host;

import demo.class_.v1.inner.Inner;

/** World imports. Implemented by the host; called by the component. */
public interface Imports {

    /** Access the imported interface. */
    Inner inner();
}
