// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.prim.v0_1.types;

/** A record with all WIT primitive types.
 *
 * @param a a WIT {@code bool}
 * @param i Unsigned 64-bit integer, range 0..2^64-1, stored as a Java {@code long},
 *          which is signed. Use {@link java.lang.Long#compareUnsigned},
 *          {@link java.lang.Long#divideUnsigned} and {@link java.lang.Long#toUnsignedString}
 *          for unsigned operations.
 * @param l A Unicode scalar value (U+0000..U+10FFFF, excluding the surrogate range
 *          U+D800..U+DFFF), stored as a Java {@code int}.
 */
public record AllPrims(
        boolean a,
        byte b,
        short c,
        int d,
        long e,
        int f,
        int g,
        long h,
        long i,
        float j,
        double k,
        int l,
        String m) {}
