// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.app.v0_2.machine.host;

import demo.app.v0_2.logging.Logging;

/** World imports. Implemented by the host; called by the component. */
public interface Imports {

    /** Access the imported interface. */
    Logging logging();

    int ping();
}
