// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.seg.v0_1.w.guest;

import demo.seg.v0_1.class_.Class;
import demo.seg.v0_1.default_.Default;

/** World imports. Called by the guest; provided by the host. */
public interface Imports {

    /** Access the imported interface. */
    Class class_();

    /** Access the imported interface. */
    Default default_();
}
