// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.sp.v0_1.types;

import io.github.witjava.support.Result;

/** WIT interface. */
public interface Types {

    Result<String, String> flip(boolean coin);
}
