// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.inline.v1.broker;

/**
 * Payload attached to every event.
 *
 * @param name Event name.
 * @param seq Unsigned 64-bit integer, range 0..2^64-1, stored as a Java {@code long}, which is signed. Use {@link java.lang.Long#compareUnsigned}, {@link java.lang.Long#divideUnsigned} and {@link java.lang.Long#toUnsignedString} for unsigned operations.
 */
public record Payload(String name, long seq) {
}
