// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.inline.v1.broker.host;

/** World exports. Called by the host; implemented by the component. */
public interface Exports {

    void log(String msg);
}
