// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.inline.v1.broker.host;

import demo.inline.v1.broker.Payload;
import demo.inline.v1.broker.Severity;

/** World imports. Implemented by the host; called by the component. */
public interface Imports {

    /**
     * @param p Unsigned 64-bit integer, range 0..2^64-1, stored as a Java {@code long}, which is signed. Use {@link java.lang.Long#compareUnsigned}, {@link java.lang.Long#divideUnsigned} and {@link java.lang.Long#toUnsignedString} for unsigned operations.
     */
    Severity onEvent(Severity sev, Payload p);
}
