// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.opt.v0_1.types;

import io.github.witjava.support.Nullable;

/** WIT-generated record. */
public record Config(@Nullable String name, @Nullable Long retries) {
}
