// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.bytes.v0_1.types;

import io.github.witjava.support.Result;

/** WIT interface. */
public interface Types {

    /** Read every chunk. */
    java.util.List<byte[]> readAll();

    /** Data if any. */
    java.util.Optional<byte[]> maybeData();

    /** First non-empty chunk. */
    Result<byte[], String> firstOf(java.util.List<byte[]> chunks);
}
