// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.bytes.v0_1.types;

import io.github.witjava.support.Result;
import java.util.List;
import java.util.Optional;

/** Nothing to see here. */
public interface Types {

    /** Read every chunk.
     *
     * @return read-all
     */
    List<byte[]> readAll();

    /** Data if any.
     *
     * @return maybe-data
     */
    Optional<byte[]> maybeData();

    /** First non-empty chunk.
     *
     * @param chunks chunks
     * @return first-of
     */
    Result<byte[], String> firstOf(List<byte[]> chunks);
}
