// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.store.v0_1.store;

/** A widget. */
public interface Widget extends AutoCloseable {

    /** Close this widget. Idempotent; corresponds to the WIT resource drop. */
    @Override
    void close();

    /** The label.
     *
     * @return label
     */
    String label();

    /** Repaint it.
     */
    void repaint();

    /** Trade for a fresh one.
     *
     * @param other Borrowed handle: ownership is not transferred by this call.
     * @return Owned handle: the caller is responsible for closing (dropping) it.
     */
    Widget swap(Widget other);

    /** Factory for {@link Widget}. */
    interface Factory {

        /** Make one.
         *
         * @param label label
         * @return create
         */
        Widget create(String label);
    }

    /** Static methods for {@link Widget}. */
    interface Statics {

        /** Two from one.
         *
         * @param w Borrowed handle: ownership is not transferred by this call.
         * @return Owned handle: the caller is responsible for closing (dropping) it.
         */
        Widget duplicate(Widget w);
    }
}
