// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.err.v1.error;

/** WIT interface. */
public interface Error_ {

    /**
     * @param e Borrowed handle: ownership is not transferred by this call.
     */
    String describe(Error e);
}
