// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.err.v1.error;

/** WIT resource. */
public interface Error extends AutoCloseable {

    /** Close this resource. Idempotent; corresponds to the WIT resource drop. */
    @Override
    void close();

    long code();
}
