// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.vef.v0_1.types;

/** Permission bits. */
public record Perms(long bits) {

    /** May read. */
    public static final Perms READ = new Perms(1L << 0);

    /** May write. */
    public static final Perms WRITE = new Perms(1L << 1);

    /** May execute. */
    public static final Perms EXEC = new Perms(1L << 2);

    public Perms or(Perms other) {
        return new Perms(bits | other.bits);
    }

    public Perms and(Perms other) {
        return new Perms(bits & other.bits);
    }

    public boolean contains(Perms other) {
        return (bits & other.bits) == other.bits;
    }

    public static Perms empty() {
        return new Perms(0L);
    }
}
