// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.vef.v0_1.types;

/** A shape. */
public sealed interface Shape permits Shape.Circle, Shape.Dot, Shape.Labeled {

    /** A circle. */
    public record Circle(double value) implements Shape {
    }

    /** A dot. */
    public record Dot() implements Shape {
    }

    /** A labeled thing. */
    public record Labeled(java.util.Optional<String> value) implements Shape {
    }
}
