// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.vef.v0_1.types;

import java.util.Optional;

/** A shape. */
public sealed interface Shape permits Shape.Circle, Shape.Dot, Shape.Labeled {

    /** A circle. */
    record Circle(double value) implements Shape {}

    /** A dot. */
    record Dot() implements Shape {}

    /** A labeled thing. */
    record Labeled(Optional<String> value) implements Shape {}
}
