package demo:vef@0.1.0;

interface types {
    /// Colors.
    enum color {
        /// Red.
        red,
        /// Dark green.
        dark-green,
    }
    /// A shape.
    variant shape {
        /// A circle.
        circle(f64),
        /// A dot.
        dot,
        /// A labeled thing.
        labeled(option<string>),
    }
    /// Permission bits.
    flags perms {
        /// May read.
        read,
        /// May write.
        write,
        /// May execute.
        exec,
    }
    record hold {
        s: shape,
        c: color,
        p: perms,
    }
}
