// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT

package demo.empty.v0_1.app.host;

import demo.empty.v0_1.used.Used;

/** World imports. Implemented by the host; called by the component. */
public interface Imports {

    /** Access the imported interface. */
    Used used();
}
