// @generated by wit-java 0.0.0, mapping v1 — DO NOT EDIT
package demo.mang.v0_1.mangled;

/** A pair.
 *
 * @param toString_ to-string
 * @param hashCode_ hash-code
 * @param equals_ equals
 */
public record Pair(String toString_, long hashCode_, boolean equals_) {}
